# Generated by Django 4.2 on 2023-04-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type_1', models.CharField(max_length=255, verbose_name='type 1')),
                ('type_2', models.CharField(max_length=255, verbose_name='type 2')),
                ('total', models.IntegerField(verbose_name='total')),
                ('hp', models.IntegerField(verbose_name='hp')),
                ('attack', models.IntegerField(verbose_name='attack')),
                ('defense', models.IntegerField(verbose_name='defense')),
                ('sp_atk', models.IntegerField(verbose_name='SP. Atk')),
                ('sp_def', models.IntegerField(verbose_name='Sp. Def')),
                ('speed', models.IntegerField(verbose_name='speed')),
                ('generation', models.IntegerField(verbose_name='generation')),
                ('legendary', models.BooleanField(verbose_name='legendary')),
            ],
        ),
    ]
